//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beer_Olympics
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int Game_ID { get; set; }
        public string Game_Name { get; set; }
        public string Game_Type { get; set; }
        public string Game_Rules { get; set; }
        public string Game_Rules_2 { get; set; }
        public string Game_Rules_3 { get; set; }
        public string Game_Rules_4 { get; set; }
        public string Game_Rules_5 { get; set; }
        public string Game_Rules_6 { get; set; }
        public string Game_Rules_7 { get; set; }
        public string Game_Rules_8 { get; set; }
        public string Game_Rules_9 { get; set; }
        public string Game_Rules_10 { get; set; }
    }
}
