//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beer_Olympics
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int Player_ID { get; set; }
        public string Player_Name { get; set; }
        public Nullable<System.DateTime> Olympics_Date { get; set; }
        public string Team_Country_ID { get; set; }
    }
}
