//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beer_Olympics
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public System.Guid ID { get; set; }
        public Nullable<int> Team_Country_ID { get; set; }
        public string Team_Country { get; set; }
        public string Team_Member_01 { get; set; }
        public string Team_Member_02 { get; set; }
        public string Team_Member_03 { get; set; }
        public string Team_Member_04 { get; set; }
        public string Team_Member_05 { get; set; }
        public Nullable<System.DateTime> Olympics_Date { get; set; }
    }
}
